spring:
  application:
    name:d2r-terrorzone-bot

discord:
  webhook:
    url: https://discord.com/api/webhooks/1382540608194740346/QRvcrq-pM5t6DtTn_5DgKC30tWpgCSKJVI6iU2gWpU0tTLx9XpIfQE8uvJTCUKb0QNh3
zone:
  meta:
    url: https://raw.githubusercontent.com/tonutoz/d2r-terrorzone-bot/master/src/main/resources/zone-meta-by-location.json